Add more tests to NoteTest and NoteIndexerTest
Automattic/simplenote-android pull request #1256
Opened 2020-12-29 20:21 UTC by jorgecasariego

### Fix
More tests are added to the NoteTest class and the NoteIndexerTest class to increase the code coverage.

### Test
1. To check if the tests are working go from Android Studio to the **NoteTest** class or the **NoteIndexerTest** class that are in the **androidTest** package
2. Right click on any of the classes 
3. Execute Run "NoteTest" or Run "NoteIndexerTest
4. All tests should pass successfully

### Review
Only one developer is required to review these changes, but anyone can perform the review.

### Release
These changes do not require release notes.

2020-12-29 23:16 UTC, theck13 reviewed
Thanks for adding some tests!  All the tests pass as described.  I think we can optimize the test files a little while we're updating them.  Since the same values are being used in the tests, we can create a single `Note` object with the specified properties in the `setup()` method.  See the code below for example.

```java
public class NoteIndexerTest {
    private static final String DATE_STRING = "2013-09-12T20:47:03.000Z";
    private static final double DATE_DOUBLE = 1379018823037.0;
    private static final long DATE_LONG = 1379018823000L;

    private Note mNote;
    private NoteIndexer mIndexer;

    @Before
    public void setUp() throws JSONException {
        JSONObject properties = new JSONObject();
        properties.put(Note.CREATION_DATE_PROPERTY, DATE_DOUBLE);
        properties.put(Note.MODIFICATION_DATE_PROPERTY, DATE_DOUBLE);
        properties.put(Note.PUBLISH_URL_PROPERTY, "test.url.property");
        mNote = new Note("test", properties);
        mIndexer = new NoteIndexer();
    }

    @Test
    public void testIndexMillisecondDates() {
        List<Index> indexes = mIndexer.index(mNote);
        assertIndex(indexes, Note.MODIFIED_INDEX_NAME);
        assertIndex(indexes, Note.CREATED_INDEX_NAME);
    }

    @Test
    public void testConvertMillisToSeconds() {
        Calendar date = Note.numberToDate(DATE_DOUBLE);
        assertThat(date.getTimeInMillis(), is(DATE_LONG));
    }

    @Test
    public void testGetCreationDate() {
        Calendar calendar = mNote.getCreationDate();
        assertThat(calendar.getTimeInMillis(), is(DATE_LONG));
    }

    @Test
    public void testGetCreationDateString() {
        Calendar date = Note.numberToDate(DATE_DOUBLE);
        mNote.setCreationDate(date);
        assertThat(mNote.getCreationDateString(), is(DATE_STRING));
    }

    @Test
    public void testGetModificationDate() {
        Calendar calendar = mNote.getModificationDate();
        assertThat(calendar.getTimeInMillis(), is(DATE_LONG));
    }

    @Test
    public void testGetModificationDateString() {
        Calendar date = Note.numberToDate(DATE_DOUBLE);
        mNote.setModificationDate(date);
        assertThat(mNote.getModificationDateString(), is(DATE_STRING));
    }

    @Test
    public void testIsPublished() {
        mNote.setPublished(true);
        assertThat(mNote.isPublished(), is(true));
        mNote.setPublished(false);
        assertThat(mNote.isPublished(), is(false));
    }

    @Test
    public void testIsNotPublished(){
        mNote.setPublished(false);
        assertThat(mNote.isPublished(), is(false));
    }

    private void assertIndex(List<Index> indexes, String name) {
        for (Index index : indexes) {
            if (index.getName().equals(name)) {
                assertThat(String.format("Index %s had incorrect value", name), DATE_LONG, is(DATE_LONG));
                return;
            }
        }

        fail(String.format("Did not find a index with name: %s", name));
    }
}

```

```java
public class NoteTest {
    private static final String CONTENT_PREVIEW = "consectetur adipisicing elit,"
            + "sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            + "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
            + "Duis aute irure dolor in reprehenderit in voluptate velit esse cil.";
    private static final String CONTENT_TITLE = "Lorem ipsum dolor sit amet";
    private static final String CONTENT = CONTENT_TITLE + "\n" + CONTENT_PREVIEW;
    private static final String KEY = "test";

    private Note mNote;

    @Before
    public void setUp() {
        mNote = new Note(KEY);
    }

    @Test
    public void testKey() {
        assertThat(mNote.getSimperiumKey(), is(KEY));
    }

    @Test
    public void testTagString() {
        mNote.setTagString(" one two three  four ");
        assertThat(mNote.getTags(), is(tagList("one", "two", "three", "four")));
        assertThat(mNote.getTagString().toString(), is("one two three four"));
    }

    @Test
    public void testTagStringNull() {
        mNote.setTags(tagList("one", "two", "three"));
        mNote.setTagString(null);
        assertThat(mNote.getTags(), is(Collections.<String>emptyList()));
    }

    @Test
    public void testRemoveDupsFromTagString() {
        mNote.setTagString(" one two tWo three two four ");
        assertThat(mNote.getTags(), is(tagList("one", "two", "three", "four")));
        assertThat(mNote.getTagString().toString(), is("one two three four"));
    }

    @Test
    public void testParseTitleAndPreview() {
        mNote.setContent(CONTENT);
        assertThat(mNote.getTitle(), is(CONTENT_TITLE));
        assertThat(mNote.getContentPreview(), is(CONTENT_PREVIEW));
    }

    @Test
    public void testNoteDoesHaveTag() {
        Tag tag = new Tag("tag");
        tag.setName("Tag");
        mNote.setTagString("tag tag2 tag3");
        assertThat(mNote.hasTag(tag), is(true));
    }

    @Test
    public void testNoteDoesNotHaveTag() {
        Tag tag = new Tag("tag");
        tag.setName("Tag");
        mNote.setTagString("tag2 tag3");
        assertThat(mNote.hasTag(tag), is(false));
    }

    @Test
    public void testPinAndUnpinNote() {
        mNote.setPinned(true);
        assertThat(mNote.isPinned(), is(true));
        mNote.setPinned(false);
        assertThat(mNote.isPinned(), is(false));
    }

    private List<String> tagList(String... tags) {
        List<String> tagArray = new ArrayList<>(tags.length);
        Collections.addAll(tagArray, tags);
        return tagArray;
    }

    @Test
    public void testConvertNumberToDateString() {
        String dateString = "2020-12-29T14:52:00.000Z";
        String dateConverted = Note.numberToDateString(1609253520);
        assertThat(dateConverted, is(dateString));
    }

    @Test
    public void testGetContent() {
        mNote.setContent(CONTENT);
        assertThat(mNote.getContent(), is(CONTENT));
    }

    @Test
    public void testEnabledAndDisabledPreview() {
        mNote.setPreviewEnabled(true);
        assertThat(mNote.isPreviewEnabled(), is(true));
        mNote.setPreviewEnabled(false);
        assertThat(mNote.isPreviewEnabled(), is(false));
    }

    @Test
    public void testEnabledAndDisabledMarkdown() {
        mNote.setMarkdownEnabled(true);
        assertThat(mNote.isMarkdownEnabled(), is(true));
        mNote.setMarkdownEnabled(false);
        assertThat(mNote.isMarkdownEnabled(), is(false));
    }

    @Test
    public void testDeletedAndUndeletedNote() {
        mNote.setDeleted(true);
        assertThat(mNote.isDeleted(), is(true));
        mNote.setDeleted(false);
        assertThat(mNote.isDeleted(), is(false));
    }

    @Test
    public void testNoteHasChanges() {
        String tag = "tag";
        boolean isPinned = true;
        boolean isMarkdownEnabled = true;
        boolean isPreviewEnabled = true;

        mNote.setContent(CONTENT_TITLE);
        mNote.setTagString(tag);
        mNote.setPinned(isPinned);
        mNote.setMarkdownEnabled(isMarkdownEnabled);
        mNote.setPreviewEnabled(isPreviewEnabled);

        assertThat(mNote.hasChanges(CONTENT_TITLE, tag, isPinned, isMarkdownEnabled, isPreviewEnabled), is(false));

        mNote.setContent("new content");
        mNote.setTagString("new tag");
        mNote.setPinned(false);
        mNote.setMarkdownEnabled(false);
        mNote.setPreviewEnabled(false);

        assertThat(mNote.hasChanges(CONTENT_TITLE, tag, isPinned, isMarkdownEnabled, isPreviewEnabled), is(true));
    }
}

```

2020-12-30 14:21 UTC, jorgecasariego commented
Great @theck13

 I'll do it!

2020-12-30 15:02 UTC, theck13 requested changes

2020-12-30 15:02 UTC, theck13 commented on Simplenote/src/androidTest/java/com/automattic/simplenote/models/NoteIndexerTest.java
>      public void testIndexMillisecondDates() throws JSONException {
```suggestion
    public void testIndexMillisecondDates() {
```

We can remove `throws JSONException` since we're no longer putting properties in a JSON object.

2020-12-30 15:02 UTC, theck13 commented on Simplenote/src/androidTest/java/com/automattic/simplenote/models/NoteIndexerTest.java
> +    public void testGetCreationDate() throws JSONException {
```suggestion
    public void testGetCreationDate() {
```

We can remove `throws JSONException` since it's unused.

2020-12-30 15:02 UTC, theck13 commented on Simplenote/src/androidTest/java/com/automattic/simplenote/models/NoteIndexerTest.java
> +    public void testGetModificationDate() throws JSONException {
```suggestion
    public void testGetModificationDate() {
```

We can remove `throws JSONException` since it's unused.

2020-12-30 15:02 UTC, theck13 commented on Simplenote/src/androidTest/java/com/automattic/simplenote/models/NoteTest.java
>      public void setUp() throws Exception {
```suggestion
    public void setUp() {
```

We can remove `throws JSONException` since it's unused.

2020-12-30 16:17 UTC, theck13 approved these changes
The code looks good and all the tests pass.

Thanks for contributing again!

2020-12-30 16:18 UTC, merged

2020-12-30 16:20 UTC, jorgecasariego commented
thanks for all the help @theck13